Repository akaj-team/selenium-test, pull requests merged in 2018-12, with the labels that each got.

#49 Implement for new group
  src/test/java/stepdefs/group/NewGroupDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/group/NewGroupPage.java
  src/test/resources/features/group/NewGroup.feature
Labels: [status] Review Needed, [type] Task

#21 Feature - Implement test for time sheet
  src/test/java/stepdefs/timesheet/TimeSheetDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/timesheet/TimeSheetPage.java
  src/test/resources/features/timesheet/TimeSheet.feature
Labels: [status] Review Needed, [type] Task

#40 Feature/create page factory
  src/test/java/vn/asiantech/base/BasePage.java
  src/test/java/vn/asiantech/base/DriverBase.java
  src/test/java/vn/asiantech/base/PageFactory.java
  src/test/java/vn/asiantech/page/admin/AccessControlPage.java
  src/test/java/vn/asiantech/page/admin/AwardCategoryPage.java
  src/test/java/vn/asiantech/page/admin/HolidaySettingPage.java
  src/test/java/vn/asiantech/page/device/DeviceTrackingPage.java
  src/test/java/vn/asiantech/page/employee/EmployeesPage.java
  src/test/java/vn/asiantech/page/employee/editemployee/EditEmployeePage.java
  src/test/java/vn/asiantech/page/employee/newemployee/CompanyInformationPage.java
  src/test/java/vn/asiantech/page/employee/newemployee/PersonalInformationPage.java
  src/test/java/vn/asiantech/page/group/NewGroupPage.java
  src/test/java/vn/asiantech/page/home/HomePage.java
  src/test/java/vn/asiantech/page/leave/LeaveBalancePage.java
  src/test/java/vn/asiantech/page/leave/LeaveOtherPage.java
  src/test/java/vn/asiantech/page/leave/LeavePlannerPage.java
  src/test/java/vn/asiantech/page/leave/MyLeavePage.java
  src/test/java/vn/asiantech/page/login/LoginPage.java
  src/test/java/vn/asiantech/page/menu/MenuPage.java
  src/test/java/vn/asiantech/page/notice/NotificationMenuElement.java
  src/test/java/vn/asiantech/page/position/NewPositionPage.java
  src/test/java/vn/asiantech/page/position/PositionsPage.java
  src/test/java/vn/asiantech/page/project/ProjectPage.java
  src/test/java/vn/asiantech/page/team/MyTeamPage.java
  src/test/java/vn/asiantech/page/team/NewTeamFormPage.java
  src/test/java/vn/asiantech/page/team/TeamsPage.java
  src/test/java/vn/asiantech/page/timesheet/TimeSheetOthers.java
  src/test/java/vn/asiantech/page/timesheet/TimeSheetPage.java
  src/test/java/vn/asiantech/page/wiki/WikiPage.java
Labels: [status] Review Needed

#51 Fix - Refactor code
  src/test/java/stepdefs/team/MyTeamDefinitions.java
  src/test/java/vn/asiantech/page/team/MyTeamPage.java
  src/test/resources/features/team/MyTeam.feature
Labels: [status] Review Needed, [type] Bug
