Repository akaj-team/selenium-test, pull requests merged in 2018-11, with the labels that each got.

#34 Fix - Refactor code
  src/test/java/stepdefs/AuthenticateDefinitions.java
  src/test/java/stepdefs/HomeDefinitions.java
  src/test/java/stepdefs/LeavePlannerDefinitions.java
  src/test/java/stepdefs/PortalLoginDefinitions.java
  src/test/java/stepdefs/UserProfileDefinitions.java
  src/test/java/stepdefs/employee/EmployeesDefinitions.java
  src/test/java/stepdefs/team/NewTeamFormDefinitions.java
  src/test/java/stepdefs/team/TeamsDefinitions.java
  src/test/java/vn/asiantech/base/BasePage.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/base/DriverBase.java
  src/test/java/vn/asiantech/base/DriverFactory.java
  src/test/java/vn/asiantech/page/HomePage.java
  src/test/java/vn/asiantech/page/LeavePlannerPage.java
  src/test/java/vn/asiantech/page/LoginPage.java
  src/test/java/vn/asiantech/page/employee/EmployeesPage.java
  src/test/java/vn/asiantech/page/team/NewTeamFormPage.java
  src/test/java/vn/asiantech/page/team/TeamsPage.java
  src/test/resources/features/Authenticate.feature
  src/test/resources/features/Home.feature
  src/test/resources/features/LeavePlanner.feature
  src/test/resources/features/UserProfile.feature
  src/test/resources/features/employee/EmployeeFilter.feature
  src/test/resources/features/employee/EmployeeSearch.feature
  src/test/resources/features/employee/EmployeeViewsDisplay.feature
  src/test/resources/features/team/DeleteTeam.feature
  src/test/resources/features/team/NewTeam.feature
  src/test/resources/features/team/Teams.feature
  src/test/resources/features/team/UpdateTeam.feature
Labels: [status] Review Needed, [type] Bug

#6 Feature - Create Test For Notification Element
  ruleset/checkstyle-checker.xml
  src/test/java/stepdefs/NotificationElementDefinitions.java
  src/test/java/vn/asiantech/base/BasePage.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/NotificationMenuElement.java
  src/test/resources/features/NotificationEmlement.feature
Labels: [status] Review Needed, [type] Task

#22 Feature - Create test for Access Controll page
  src/test/java/stepdefs/AccessControlDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/AccessControlPage.java
  src/test/resources/features/accesscontrol/AccessControl.feature
Labels: [status] Review Needed, [type] Task

#27 Feature - Create New Employee Page
  src/test/java/stepdefs/employee/newemployee/CompanyInformationDefinitions.java
  src/test/java/stepdefs/employee/newemployee/PersonalInformationDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/employee/EmployeesPage.java
  src/test/java/vn/asiantech/page/employee/newemployee/CompanyInformationPage.java
  src/test/java/vn/asiantech/page/employee/newemployee/PersonalInformationPage.java
  src/test/resources/features/employee/newemployee/CompanyInformation.feature
  src/test/resources/features/employee/newemployee/PersonalInformation.feature
Labels: [status] Review Needed, [type] Task

#23 Feature - Create award category test
  src/test/java/stepdefs/AwardCategoryDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/AwardCategoryPage.java
  src/test/resources/features/AwardCategory.feature
Labels: [status] Review Needed, [type] Task

#2 Feature - Create my leave test
  src/test/java/stepdefs/MyLeaveDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/MyLeavePage.java
  src/test/resources/features/MyLeave.feature
Labels: [status] Review Needed, [type] Task

#25 Feature - Implement holiday setting
  src/test/java/stepdefs/HolidaySettingDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/HolidaySettingPage.java
  src/test/resources/features/HolidaySetting.feature
Labels: [status] In-Progress, [type] Task

#3 Feature - Create menu test
  src/test/java/stepdefs/MenuDefinitions.java
  src/test/java/vn/asiantech/page/MenuPage.java
  src/test/resources/features/MenuImplement.feature
Labels: [status] Review Needed

#26 Implement for submit device tracking
  src/test/java/stepdefs/DeviceTrackingDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/DeviceTrackingPage.java
  src/test/resources/features/DeviceTracking.feature
Labels: [status] In-Progress, [type] Task

#15 Feature - Create Test LeaveBalance & Project Page
  ruleset/checkstyle-checker.xml
  src/test/java/stepdefs/LeaveBalanceDefinitions.java
  src/test/java/stepdefs/ProjectsDefinitions.java
  src/test/java/vn/asiantech/base/BasePage.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/base/DriverBase.java
  src/test/java/vn/asiantech/page/LeaveBalancePage.java
  src/test/java/vn/asiantech/page/ProjectPage.java
  src/test/resources/features/LeaveBalance.feature
  src/test/resources/features/Projects.feature
Labels: [status] Review Needed, [type] Task

#13 Feature - Positions
  src/test/java/stepdefs/PositionsDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/PositionsPage.java
  src/test/resources/features/Positions.feature
Labels: [status] Review Needed, [type] Task

#41 Fix - Refactor Code
  src/test/java/stepdefs/leave/LeaveBalanceDefinitions.java
  src/test/java/stepdefs/position/PositionsDefinitions.java
  src/test/java/stepdefs/project/ProjectsDefinitions.java
  src/test/java/vn/asiantech/page/leave/LeaveBalancePage.java
  src/test/java/vn/asiantech/page/position/PositionsPage.java
  src/test/java/vn/asiantech/page/project/ProjectPage.java
  src/test/resources/features/leave/LeaveBalance.feature
  src/test/resources/features/position/Positions.feature
  src/test/resources/features/project/Projects.feature
Labels: [status] Review Needed, [type] Bug

#42 create test new position
  src/test/java/stepdefs/position/NewPositionDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/position/NewPositionPage.java
  src/test/resources/features/position/NewPosition.feature
Labels: [status] Review Needed, [type] Task

#8 Feature - TimeSheet others page
  src/test/java/stepdefs/timesheet/TimeSheetOthersDefinitions.java
  src/test/java/vn/asiantech/base/BasePage.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/timesheet/TimeSheetOthers.java
  src/test/resources/features/timesheet/TimeSheetOthers.feature
Labels: [status] Review Needed, [type] Task

#43 Feature - Create test new award page
  src/test/java/stepdefs/admin/AwardCategoryDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/admin/AwardCategoryPage.java
  src/test/resources/features/admin/AwardCategory.feature
Labels: [status] Review Needed, [type] Task

#45 Feature - Edit Employee
  src/test/java/stepdefs/employee/EmployeesDefinitions.java
  src/test/java/stepdefs/employee/editemployee/EditEmployeeDefinitions.java
  src/test/java/vn/asiantech/object/Employee.java
  src/test/java/vn/asiantech/page/employee/EmployeesPage.java
  src/test/java/vn/asiantech/page/employee/editemployee/EditEmployeePage.java
  src/test/java/vn/asiantech/page/employee/newemployee/PersonalInformationPage.java
  src/test/resources/features/employee/EmployeeViewsDisplay.feature
  src/test/resources/features/employee/editemployee/EditEmployee.feature
Labels: [status] Review Needed, [type] Task

#47 Fix - Update device tracking
  src/test/java/stepdefs/device/DeviceTrackingDefinitions.java
  src/test/java/vn/asiantech/page/device/DeviceTrackingPage.java
  src/test/resources/features/device/DeviceTracking.feature
Labels: [status] Review Needed, [type] Bug

#44 Feature - Update team page
  src/test/java/stepdefs/team/NewTeamFormDefinitions.java
  src/test/java/stepdefs/team/TeamsDefinitions.java
  src/test/java/vn/asiantech/page/team/NewTeamFormPage.java
  src/test/java/vn/asiantech/page/team/TeamsPage.java
  src/test/resources/features/team/DeleteTeam.feature
  src/test/resources/features/team/NewTeam.feature
  src/test/resources/features/team/UpdateTeam.feature
Labels: [status] Review Needed
