Repository akaj-team/selenium-test, pull requests merged in 2018-10, with the labels that each got.

#14 Feature - Create automation test convention
  Convention.md
Labels: [status] Review Needed, [type] Task

#24 Feature - Update ids for leave planners page
  src/test/java/stepdefs/LeavePlannerDefinitions.java
  src/test/java/vn/asiantech/base/DriverBase.java
  src/test/java/vn/asiantech/page/LeavePlannerPage.java
  src/test/resources/features/LeavePlanner.feature
Labels: [status] Review Needed, [type] Task

#9 Feature - Create auto test for home page
  src/test/java/stepdefs/HomeDefinitions.java
  src/test/java/vn/asiantech/page/HomePage.java
  src/test/resources/features/Home.feature
Labels: [status] Review Needed, [type] Task

#31 Feature - Update CI Rule CheckStyle
  ruleset/checkstyle-checker.xml
Labels: [status] Review Needed, [type] Task

#32 Fix more error when wait element
  src/test/java/stepdefs/HomeDefinitions.java
  src/test/java/stepdefs/team/TeamsDefinitions.java
Labels: [status] Review Needed

#11 Feature - Create Employee Test
  src/test/java/stepdefs/employee/EmployeesDefinitions.java
  src/test/java/vn/asiantech/page/employee/EmployeesPage.java
  src/test/resources/features/UserProfile.feature
  src/test/resources/features/employee/EmployeeFilter.feature
  src/test/resources/features/employee/EmployeeSearch.feature
  src/test/resources/features/employee/EmployeeViewsDisplay.feature
Labels: [status] Review Needed, [type] Task

#30 Feature - Update Flow Login Without Logout And A Unique User
  src/test/java/stepdefs/AuthenticateDefinitions.java
  src/test/java/stepdefs/HomeDefinitions.java
  src/test/java/stepdefs/PortalLoginDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/base/DriverFactory.java
  src/test/java/vn/asiantech/page/LoginPage.java
  src/test/resources/features/Authenticate.feature
  src/test/resources/features/PortalLogin.feature
Labels: [status] Review Needed, [type] Task

#33 Fix - Some Error Cases In Master Branch
  pom.xml
  src/test/java/stepdefs/HomeDefinitions.java
  src/test/java/stepdefs/LeavePlannerDefinitions.java
  src/test/java/stepdefs/UserProfileDefinitions.java
  src/test/java/stepdefs/team/NewTeamFormDefinitions.java
  src/test/java/stepdefs/team/TeamsDefinitions.java
  src/test/java/vn/asiantech/page/HomePage.java
  src/test/java/vn/asiantech/page/LeavePlannerPage.java
  src/test/java/vn/asiantech/page/employee/EmployeesPage.java
  src/test/java/vn/asiantech/page/team/TeamsPage.java
  src/test/resources/features/team/NewTeam.feature
  src/test/resources/features/team/UpdateTeam.feature
Labels: [status] Review Needed, [type] Bug
