Repository akaj-team/selenium-test, pull requests merged in 2019-01, with the labels that each got.

#37 feature/create test with parallel
  pom.xml
  src/test/java/stepdefs/login/AuthenticateDefinitions.java
  src/test/java/stepdefs/login/PortalLoginDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/base/CucumberRunnerBase.java
  src/test/java/vn/asiantech/base/DriverBase.java
  src/test/java/vn/asiantech/base/DriverFactory.java
  src/test/resources/DefaultSuite.xml
  src/test/resources/GridParallelSuite.xml
  src/test/resources/ParallelSuite.xml
  src/test/resources/TestSuite.xml
  src/test/resources/features/login/PortalLogin.feature
Labels: [status] Review Needed

#48 Feature - Automation Test Document
  Document.md
Labels: [status] Review Needed, [type] Task

#59 Fix - Run Test Parallel
  src/test/java/ChromeTestRunner.java
  src/test/java/DefaultTestRunner.java
  src/test/java/FirefoxTestRunner.java
  src/test/java/vn/asiantech/base/DriverFactory.java
  src/test/resources/DefaultSuite.xml
  src/test/resources/GridParallelSuite.xml
  src/test/resources/ParallelSuite.xml
Labels: [status] Review Needed, [type] Bug

#46 Feature - Create child page new wiki page
  src/test/java/stepdefs/wiki/NewWikiDefinition.java
  src/test/java/stepdefs/wiki/UpdateWikiDefinition.java
  src/test/java/stepdefs/wiki/WikiDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/wiki/NewWikiPage.java
  src/test/java/vn/asiantech/page/wiki/UpdateWikiPage.java
  src/test/resources/features/wiki/NewWiki.feature
  src/test/resources/features/wiki/UpdateWiki.feature
Labels: [status] Review Needed, [type] Task

#16 Feature - Create leave request test
  src/test/java/stepdefs/leave/LeaveRequestDefinitions.java
  src/test/java/stepdefs/leave/MyLeaveDefinitions.java
  src/test/java/vn/asiantech/base/Constant.java
  src/test/java/vn/asiantech/page/leave/LeaveRequestPage.java
  src/test/java/vn/asiantech/page/wiki/NewWikiPage.java
  src/test/resources/features/leave/LeaveRequest.feature
  src/test/resources/features/project/NewProject.feature
Labels: [status] Review Needed, [type] Task

#60 Fix - Double Step
  src/test/java/stepdefs/leave/LeaveRequestDefinitions.java
  src/test/resources/features/leave/LeaveRequest.feature
Labels: [status] Review Needed, [type] Bug
